// 配置文件

export default {

  DROPS_CLASS: 5,
  DROPS_VALVE_CLASS: 13,
  PUMP_CLASS: 3,
  FERTILIZER_CLASS: 6,
  SOIL_CLASS: 8,
  WEATHER_CLASS: 7,
  SPRAY_CLASS: 4,
  SPRAY_VALVE_CLASS: 13,
  NDVI_CLASS: 17,
  HEIGHT_CLASS: 18,
  CANOPY_CLASS: 12,

  MQTT_TOPIC: 'D/0103.0007.1921000133/#',
  MQTT_HOST: 'www.zesi.com.cn',
  MQTT_PORT: 443,
  MQTT_ADDR: '/mqtt',
  MQTT_USETLS: true,
  MQTT_USERNAME: 'user',
  MQTT_PASSWORD: 'Dev1"3$5',
  MQTT_CLEANSESSION: false,
  MQTT_TIMEOUT: 10

}
